FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic AS base

COPY /EHC.API/certs/ehc.qa.crt /EHC.API/certs/CA1.crt /EHC.API/certs/CA2.crt /EHC.API/certs/Root.crt /usr/local/share/ca-certificates/
RUN cd /usr/local/share/ca-certificates && update-ca-certificates

WORKDIR /app
EXPOSE 80

# Copy files from the artifact staging folder on agent
COPY EHC.API/out .

ENTRYPOINT ["dotnet", "Tlm.EHC.API.dll"]
