#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using IdentityModel;
using Microsoft.AspNetCore.Http;
using Polly;
using Serilog;
using Tlm.Sdk.Api;
using Tlm.Sdk.AspNetCore;
using Tlm.Sdk.Core;

namespace TLM.EHC.API
{
    /// <summary>
    /// Provides URI parts based on configured values.
    /// </summary>
    public class EHCConfigUriPartProvider : UriPartProvider
    {
        private HostingConfig _config;
        private static readonly ILogger Logger = Log.Logger.ForContext<EHCConfigUriPartProvider>();

        public EHCConfigUriPartProvider(IHttpContextAccessor accessor, HostingConfig config) : base(accessor, config)
        {
            _config = config;
            Logger.Information("Config Base url is: " + _config.BaseUrl);
        }
        
        public override string Path => Context.Request.Path.Value.SanitizeAndLower();

        public override string BaseUrl => _config.BaseUrl != null ? _config.BaseUrl.SanitizeAndLower() : null;


        public override string HostName => null;

        public override string Scheme => null;

        public override UriPartProviderId Identity => UriPartProviderId.Config;

    }
}
