#region Header

// Schlumberger Private
// Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Net.Http;
using System.Threading.Tasks;
using FluentAssertions;
using IdentityModel.Client;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using NSubstitute;
using TLM.EHC.API.Controllers;
using TLM.EHC.Common.Historian;
using TLM.EHC.API.ResponseProviders;
using TLM.EHC.Common;
using TLM.EHC.Common.Models;
using Tlm.Sdk.Testing.Unit;

namespace EHC.API.Tests.ResponseProviders
{
    [UnitTestCategory]
    [TestClass]
    public class ResponseProviderInfluxTest
    {
        private Mock<IUrlBuilder> _urlBuilder;
        private EhcApiConfig _config;

        [TestInitialize]

        public void TestInitialize()
        {
            _config = ConfigDetails();
            _urlBuilder = new Mock<IUrlBuilder>();
        }
        public EhcApiConfig ConfigDetails()
        {
            return new EhcApiConfig()
            {
                InfluxDB = new ExternalApi()
                {
                    BaseUrl = "testInfluxDb.slb.com",
                    Username = "testInflux",
                    Password = "test@123"
                }
            };
        }

        [TestMethod]
        public async Task Test_GetResponse()
        {
            var responseProvider = GetResponseProviderInflux();
            var dummyEquipment = new Equipment()
            {
                EquipmentCode = "SPF-743",
                EquipmentWkeId = "100949474:1396533",
                MaterialNumber = "100949474",
                SerialNumber = "1396533",
                SourceSystemRecordId = "1396533"
            };

            var mockQuery = new Query("DXP_WPS_PUMPING_EQUIPMENT",
                "SELECT * FROM STIMULATION_PUMP_WS - 67 WHERE EquipmentInstance='100949474:1396533' AND time >= 1564327807293000000 AND time <= 1564414207293000000");
            var mockQueryContext = new QueryContext()
            {
                Equipment = dummyEquipment
            };
            _urlBuilder.Setup(x =>
                x.GetQueryUrl(It.IsAny<Query>())).Returns("https://www.google.com/");
            var res = await responseProvider.GetResponse(mockQuery, mockQueryContext);
            res.Should().NotBeNull();
            Assert.AreEqual(typeof(ApiResponse), typeof(ApiResponse));
        }

        [TestMethod]
        public async Task Test_GetNoResponse()
        {
            var dummyRowsrequest = new RowsRequest()
            {
                WKEid = new WellKnownEntityId("3223452", "SPF743786"),
                Codes = new[] { "time", "AirPressure" },
                DataType = DataType.Episodic,
                QueryType = QueryType.SingleCode,
                TimePeriod = new TimePeriod(DateTime.Now, DateTime.Now.AddDays(10)),
                EpisodeId = "247329847293",
                ResponseFormat = ResponseFormat.Influx
            };

            var dummyEquipment = new Equipment()
            {
                EquipmentCode = "SPF-743",
                EquipmentWkeId = "100949474:1396533",
                MaterialNumber = "100949474",
                SerialNumber = "1396533",
                SourceSystemRecordId = "1396533"
            };

            var responseProvider = GetResponseProviderInflux();
            var mockQueryContext = new QueryContext()
            {
                Equipment = dummyEquipment
            };
            var result = await responseProvider.GetResponseNoData(dummyRowsrequest, mockQueryContext);
            result.Should().NotBeNull();
            result.Should().BeOfType<ApiResponse>();
        }

        [TestMethod]
        public void Test_GetLatestTimeStampThroughQueryUrl()
        {
            var urlBuilder = new UrlBuilder(ConfigDetails());
            string finalUrl = urlBuilder.GetLatestTimeStampThroughQueryUrl("DXJ_WPS_BLENDING_EQUIPMENT", "DXJ_WPS_BLENDING_EQUIPMENT",
                "WS - 63_STIMULATION_BLENDER_PROP", "1645703106337000000");
            finalUrl.Should().NotBeEmpty();
            finalUrl.Should().BeOfType(typeof(string));
            Assert.AreEqual("testInfluxDb.slb.com/query?db=DXJ_WPS_BLENDING_EQUIPMENT&q=SELECT * FROM DXJ_WPS_BLENDING_EQUIPMENT.\"autogen\".WS - 63_STIMULATION_BLENDER_PROPWHERE TIME<1645703106337000000 GROUP BY \"EquipmentInstance\" ORDER BY DESC LIMIT 1", finalUrl);
        }

        [TestMethod]
        public void Test_GetLatestTimeStampForChannel()
        {
            var urlBuilder = new UrlBuilder(ConfigDetails());
            string finalUrl = urlBuilder.GetLatestTimeStampForChannel("DXJ_WPS_BLENDING_EQUIPMENT", "AirPressure.kPa",
                "DXJ_WPS_BLENDING_EQUIPMENT", "WS - 63_STIMULATION_BLENDER_PROP", "1645703106337000000");
            finalUrl.Should().NotBeNullOrEmpty();
            finalUrl.Should().BeOfType(typeof(string));
            Assert.AreEqual("testInfluxDb.slb.com/query?db=DXJ_WPS_BLENDING_EQUIPMENT&q=SELECT+%22AirPressure.kPa%22+FROM+WS+-+63_STIMULATION_BLENDER_PROP+WHERE+TIME%3c1645703106337000000+GROUP+BY+%22EquipmentInstance%22+ORDER+BY+DESC+LIMIT+1", finalUrl);
        }

        [TestMethod]
        public void Verify_GetUrlShowDatabases()
        {
            var urlBuilder = new UrlBuilder(ConfigDetails());
            string queryUrl = urlBuilder.GetUrlShowDatabases();
            queryUrl.Should().NotBeNullOrEmpty();
            queryUrl.Should().BeOfType(typeof(string));
            Assert.AreEqual("testInfluxDb.slb.com/query?pretty=true&q=show+databases", queryUrl);
        }

        [TestMethod]
        public void Verify_GetUrlCreateDatabase()
        {
            string dbName = "DXP_WPS_PUMPING_EQUIPMENT";
            var urlBuilder = new UrlBuilder(ConfigDetails());
            string queryUrl = urlBuilder.GetUrlCreateDatabase(dbName);
            queryUrl.Should().NotBeNullOrEmpty();
            queryUrl.Should().BeOfType(typeof(string));
            Assert.AreEqual("testInfluxDb.slb.com/query?q=create+database DXP_WPS_PUMPING_EQUIPMENT", queryUrl);
        }

        protected ResponseProviderInflux GetResponseProviderInflux()
        {
            return new ResponseProviderInflux(new HttpClientFake(), _urlBuilder.Object, _config);
        }

        public class HttpClientFake : IHttpClientFactory
        {

            public void Clear()
            {

            }

            public static void BasicAuthentication()
            {
                string username = "test";
                string password = "test@123";

                HttpClient client = new HttpClient();
                client.SetBasicAuthentication(username, password);
            }

            public HttpClient CreateClient(string name)
            {
                return new HttpClient();
            }

            public HttpResponseMessage GetAsync()
            {
                return new HttpResponseMessage();
            }
        }


    }



}
